### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by rezraf** [PheeZz/wireguard-bot#2]
● wireguard-bot.service - 'Service for wireguard bot'
     Loaded: loaded (/etc/systemd/system/wireguard-bot.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-05-19 22:15:27 UTC; 2s ago
    Process: 1046372 ExecStart=/bin/bash -c cd ~/wireguard-bot/ && source .venv/bin/activate && python3 app.py (code=ex>
   Main PID: 1046372 (code=exited, status=1/FAILURE)
        CPU: 1ms

May 19 22:15:27 rezrafserver systemd[1]: wireguard-bot.service: Scheduled restart job, restart counter is at 5.
May 19 22:15:27 rezrafserver systemd[1]: Stopped 'Service for wireguard bot'.
May 19 22:15:27 rezrafserver systemd[1]: wireguard-bot.service: Start request repeated too quickly.
May 19 22:15:27 rezrafserver systemd[1]: wireguard-bot.service: Failed with result 'exit-code'.
May 19 22:15:27 rezrafserver systemd[1]: Failed to start 'Service for wireguard bot'.

**Comment by rezraf** [comment]
(.venv) root@rezrafserver ~/wireguard-bot-master # python3 app.py
Traceback (most recent call last):
  File "/root/wireguard-bot-master/app.py", line 36, in <module>
    from handlers import dp
  File "/root/wireguard-bot-master/handlers/__init__.py", line 1, in <module>
    from .user import *
  File "/root/wireguard-bot-master/handlers/user.py", line 7, in <module>
    from middlewares import rate_limit
  File "/root/wireguard-bot-master/middlewares/__init__.py", line 2, in <module>
    from loader import dp
  File "/root/wireguard-bot-master/loader.py", line 5, in <module>
    from utils.vpn_cfg_work import wireguard_config
  File "/root/wireguard-bot-master/utils/vpn_cfg_work.py", line 3, in <module>
    import database
  File "/root/wireguard-bot-master/database/__init__.py", line 2, in <module>
    from .selector import *
  File "/root/wireguard-bot-master/database/selector.py", line 174
    match days:
          ^

**Comment by rezraf** [comment]
фикс версии помог
